apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cicd-jenkins:1.0.0-38
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-cicd-jenkins:1.0.0-38
  template:
    metadata:
      labels:
        app: kubernetes-cicd-jenkins:1.0.0-38
    spec:
      containers:
        - name: kubernetes-cicd-jenkins:1.0.0-38
          image: sadi1234/kubernetes-cicd-jenkins:1.0.0-38
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
